apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config
  # labels:
  #   type: local
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/felipe/jellyfin/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - walnut
