apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-config
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/felipe/jellyfin/app-config/prowlarr
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - walnut
