apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-config
  namespace: media
spec:
  storageClassName: ""
  volumeName: seerr-config
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
